---
title: "R Notebook"
output: html_notebook
---


```{r}

3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"


-6*5+2>= -10+1

"raining" <="table"

TRUE > FALSE

linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15

facebook <=10

linkedin > facebook

vistas <-matrix(c(linkedin,facebook),nrow=2,byrow = TRUE)


vistas ==13

vistas <=10


linkedin <=10

linkedin <=10 & facebook==13

linkedin <=10 | facebook==13

medium <- "Linkedin"

num_views <-14

if(medium == "Linkedin")
{
  print("showing linkedin information")
}

if(medium == "Linkedin")
{
  print("showing linkedin information")
}else{
  print("unknow medium")
}

if(medium == "Linkedin")
{
  print("showing linkedin information")
}else if(medium=="facebook"){
  print("Facebook")
}else{
  print("unknow medium")
}

number <-75
result <-""

if(number < 10){
  if(number <5){
    result <- "extra small"
  }else{
    result <-"small"
  }
}else if(number < 100){
  result <- "medium"
}else {
  resutl <-"large"
}

print (result)



```

ciclos
```{r}
speed <-64

while (speed>30){
  print(paste("you speed is",speed))
  if(speed >=48){
    print("slow down big time")
    speed<- speed-11
  }else{
    print("Slow down")
    speed<-speed-6
  }
}

speed


```

break
```{r}

speed <-88

while (speed>30){
  print(paste("you speed is",speed))
  if(speed >=80){
    break
  }
  if(speed>48)
  {print("Slow down big time")
    speed <-speed-11
   }else{
    print("Slow down")
    speed<-speed-6
  }
}

```
for
```{r}

linkedin <- c(16,9,13,5,2,17,14)

for(l in linkedin){
  print(l)
  
}

for(i in 1:length(linkedin)){
  print(linkedin[i])
}


```
loop over a list
```{r}

my <- list(pop=8405837, boroughs=c("manhattan","bronx","brooklyn","queens","staten island"), capital=FALSE )

for( n in my ){
  print(n)
}

for( i in 1:length(my) ){
  print(my[i])
}

views <- matrix(c(linkedin,facebook), nrow=2, byrow=TRUE)

for(row in 1:nrow(views)){
  for(col in 1:ncol(views)){
    print(paste("on row",row,"and column",col,"contaings",views[row,col]))
  }
}

```

