---
title: "sesion 5"
output: html_notebook
---

```{r}
library(gapminder)
library(dplyr)

gapminder

gapminder %>% filter(year==1957)

gapminder %>% arrange(lifeExp)

gapminder %>% arrange(desc(lifeExp))

gapminder %>% 
  filter(year==1957) %>% 
  arrange(desc(pop))


```
funcion mutate verb

```{r}

gapminder %>%
  filter(year==1957) %>%
  mutate(lifeExpMonths=12 * lifeExp) %>%
  arrange(desc(lifeExpMonths))

  
```
funcion rip para leer csv

visualisacion con ggplot2

```{r}

library(ggplot2)

gapminder_1952 <- gapminder %>% filter(year==1957)

ggplot(gapminder_1952,aes(x=pop, y=gdpPercap))+ geom_point()

ggplot(gapminder_1952,aes(x=pop, y=gdpPercap))+ geom_point() + scale_x_log10()+
scale_y_log10()

ggplot(gapminder_1952,aes(x=pop, y=lifeExp, color=continent))+ geom_point() + scale_x_log10()+
scale_y_log10()



```
Log scaling

```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```
Colors
```{r}
gapminder_1952
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```
```{r}
View(gapminder_1952)
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent, size=gdpPercap)) + 
  geom_point() +
  scale_x_log10()
```
Facetado
```{r}
View(gapminder_1952)
ggplot(gapminder_1952, aes(x=pop, y=lifeExp)) + 
  geom_point() +
  scale_x_log10() +
  #scale_y_log10() +
  facet_wrap(~continent)
```

```{r}
ggplot(gapminder, aes(x=gdpPercap, y=lifeExp)) + 
  geom_point() +
  scale_x_log10() +
  facet_wrap(~year)
```
