---
title: "SESION 6"
output: html_notebook


---


```{r}
library(tidyverse)
library(gapminder)
gapminder %>%
  summarize(medianLifeExp = median(lifeExp))
gapminder %>%
  filter(year == 1957) %>%
  summarize(medianLifeExp = median(lifeExp))
gapminder %>%
  filter(year == 1957) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
```
```{r}
gapminder %>%
  group_by(continent) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
```
```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
```

```{r}
library(ggplot2)
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
by_year
ggplot(by_year, aes(x=year, y=medianLifeExp)) +
  geom_point()
```
Grafica de Puntos
```{r}
by_year_cont <- gapminder %>%
  group_by(continent, year) %>%
  summarize(mediangdpPercap = median(gdpPercap))
by_year_cont
ggplot(by_year_cont, aes(x=year, y=mediangdpPercap, color=continent)) +
  geom_point()
```
Grafica de Lineas
```{r}
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(mediangdpPercap = median(gdpPercap))
by_year
ggplot(by_year, aes(x=year, y=mediangdpPercap)) +
  geom_line()
```
```{r}
by_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarize(mediangdpPercap = median(gdpPercap))
by_continent
ggplot(by_continent, aes(x=year, y=mediangdpPercap, color=continent)) +
  geom_line()
```
Grafica de Barras/Columnnas
```{r}
oceania_1952 <- gapminder %>%
  filter(continent =="Oceania", year == 1952)
oceania_1952
ggplot(oceania_1952, aes(x=country, y=gdpPercap, fill=country)) +
  geom_col()
```
Grafica Histograma
```{r}
library(tidyverse)
library(gapminder)
library(ggplot2)
gapminder_1952 <- gapminder %>%
  filter(year == 1952) %>%
  mutate(pop_by_mil = pop/1000000)
gapminder_1952
ggplot(gapminder_1952, aes(x=pop_by_mil)) +
  geom_histogram(bins=50)
ggplot(gapminder_1952, aes(x=pop)) +
  geom_histogram(bins=50) +
  scale_x_log10()
```
Grafica Box plots
```{r}
library(tidyverse)
library(gapminder)
library(ggplot2)
gapminder_1952 <- gapminder %>%
  filter(year == 1952)
gapminder_1952
ggplot(gapminder_1952, aes(x=continent, y=gdpPercap)) +
  geom_boxplot() +
  scale_y_log10()
```
Data manipulation with dplyr
```{r}
library(tidyverse)
counties <- read_csv ('C:/Users/edcan/Downloads/counties.csv')
view(counties)
counties %>%
  select_("state", "county", "population", "men", "women") %>%
  mutate(men_proportion=men/population) %>%
  filter (population > 1000) %>%
  arrange(desc(men_proportion))
```

```{r}

count_select <-counties %>%
  select_("region", "county", "population", "state", "citizens","walk")

count_select2 <-counties %>%
  select("region")


  select("region", "county", "population", "state", "citizens")


count_select %>%
  count(region, sort=TRUE)


count_select %>%
  count(state)

count_select %>%
  count(state, wt = citizens)

count_select %>%
  count(state, wt = citizens) %>%
  arrange(desc(n))


count_select %>%
  mutate(population_walk=population*walk/100) %>%
  count(state,wt=population_walk,sort=TRUE)

test<-count_select %>%
  mutate(population_walk=population*walk/100) %>%
  count(state,wt=population_walk,sort=TRUE)

test %>%
  select_("state", numeber=n)


```

```{r}

count_select <- counties %>%
  select_("county","population","income","unemployment")

count_select %>%
  summarize(min_population=min(population),max_unemployment=max(unemployment), average_income= mean(income))

count_select <- counties %>%
  select_("county","state","population","land_area")


count_select %>%
  group_by(state) %>%
  summarize(total_area=sum(land_area,total_population=sum(population)))

count_select <- counties %>%
  select_("region","state","population","county")

count_select %>%
  group_by(region,state) %>%
  summarize(total_po=sum(population)) %>%
  summarize(average_pop=mean(total_po),median_pop=median(total_po))



count_select %>%
  group_by(region,state) %>%
  summarize(total_po=sum(population)) %>%
  ungroup() %>%
  summarize(average_pop=mean(total_po),median_pop=median(total_po))


```
the top_n verb

```{r}

count_select <- counties %>%
  select_("region","state","population","metro","walk")

count_select %>%
  group_by(region) %>%
  top_n(1,walk)


count_select <- counties %>%
  select_("region","state","population","metro","walk","income")

count_select %>%
  group_by(region,state) %>%
  summarize(average_income=mean(income)) %>%
  ungroup() %>%
  top_n(1,average_income)


  top_n(1,walk)

```
```{r}
count_select <- counties %>%
  select_("state","population","metro")

count_select %>%
  group_by(state,metro) %>%
  summarize(total_pob=sum(population))%>%
  top_n(1,total_pob) %>%
ungroup() %>%
  count(metro, st=total_pob)



```

